<a href="https://colab.research.google.com/github/kitadev070/MyAngularApp/blob/master/1_tensor_ipynb_%E3%81%AE%E3%82%B3%E3%83%94%E3%83%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# tensor

https://yutaroogawa.github.io/pytorch_tutorials_jp/

テンソルは特殊なデータ構造で、配列や行列によく似ています。
PyTorchではテンソル型の変数を使用して、モデルの入力と出力、そしてモデルのパラメータを表現します。

テンソルはNumPyのndarraysに似ていますが、違いとしてGPUや他のハードウェアアクセラレータ上で動作させることができます。
テンソルとNumPyの配列は基本的には同じメモリを共有することができるため、2つの型間での変換時にはデータをコピーする必要がありません。

テンソルはその他に、自動微分に最適化されています（この点については、後ほど5. 自動微分にて、詳しく説明します）。

In [ ]:
import torch
import numpy as np

## 1. tensorの作成

### 1) データから直接作成

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


### 2) numpy ndarrayからtensorに変換

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(type(np_array));
print(np_array)
print(x_np)
print(type(x_np))

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


### 3) random値や定数のtensorの作成

In [ ]:
shape=(2, 3)
zeros_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)
rand_tensor = torch.rand(shape)

print(zeros_tensor)
print(ones_tensor)
print(rand_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8896, 0.7255, 0.0301],
        [0.4423, 0.6200, 0.9527]])


## 2. numpyとtensorでメモリの共有
### tensorからnumpyへ変換

In [ ]:
rand_np = rand_tensor.numpy()
print(type(rand_np))
print(rand_np)

<class 'numpy.ndarray'>
[[0.8895748  0.7255027  0.03008831]
 [0.44234514 0.62000823 0.95269996]]


### CPUメモリの共有

In [ ]:
rand_np[:,1] = 0 

print(rand_np)
print(rand_tensor)

[[0.8895748  0.         0.03008831]
 [0.44234514 0.         0.95269996]]
tensor([[0.8896, 0.0000, 0.0301],
        [0.4423, 0.0000, 0.9527]])


## 3. GPUメモリへ移動

In [ ]:
import torch

X = torch.rand(2, 2)
print(X)
if torch.cuda.is_available():
    Y = X.to('cuda')
print(Y)

tensor([[0.2615, 0.0592],
        [0.6280, 0.9563]])
tensor([[0.9733, 0.5160],
        [0.5958, 0.3341]])


In [ ]:
Z = Y @ Y
print(Z)

tensor([[1.2547, 0.6746],
        [0.7789, 0.4190]])


In [ ]:
X[:,1] = 0
print(X)
print(Y)
print(Z)

tensor([[0.2615, 0.0000],
        [0.6280, 0.0000]])
tensor([[0.9733, 0.5160],
        [0.5958, 0.3341]])
tensor([[1.2547, 0.6746],
        [0.7789, 0.4190]])


## 4.tensorの演算

In [ ]:
import torch
X = torch.randint(low=1, high=9, size=(2,2,))
Y = torch.randint(low=1, high=9, size=(2,2,))
print(X)
print(Y)

tensor([[4, 1],
        [7, 7]])
tensor([[5, 4],
        [8, 7]])


In [ ]:
print(X + Y)
print(X - Y)
print(X * Y)
print(X / Y)
print(X % Y)
print(X @ Y)

tensor([[ 9,  5],
        [15, 14]])
tensor([[-1, -3],
        [-1,  0]])
tensor([[20,  4],
        [56, 49]])
tensor([[0.8000, 0.2500],
        [0.8750, 1.0000]])
tensor([[4, 1],
        [7, 0]])
tensor([[28, 23],
        [91, 77]])
